-- Fix rating chain for user e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b
-- Generated by scripts/fix_rating_chain.ts
-- 2026-02-23T18:08:02.523Z
-- Chain breaks: 2, Records updated: 58
BEGIN;

-- Session: 8263132b-6e34-4e5f-b6fd-d54757b7130d
-- id=2958 [win]: before 1788.06023 → 1862.64630, after 1810.34336 → 1869.04124
UPDATE public.match_history SET
  user_rating_before = 1862.64630322759,
  user_rating_after = 1869.0412447409874,
  user_rd_before = 90.724882440776,
  user_rd_after = 89.90421049907546,
  user_vol_before = 0.0599772009071612,
  user_vol_after = 0.059975937727302774,
  rating_change = 6.394941513397498
WHERE id = 2958 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2959 [win]: before 1810.34336 → 1869.04124, after 1821.99924 → 1872.72889
UPDATE public.match_history SET
  user_rating_before = 1869.0412447409874,
  user_rating_after = 1872.7288885229275,
  user_rd_before = 89.90421049907546,
  user_rd_after = 89.63975184160745,
  user_vol_before = 0.059975937727302774,
  user_vol_after = 0.059975073971465655,
  rating_change = 3.6876437819400962
WHERE id = 2959 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2960 [win]: before 1821.99924 → 1872.72889, after 1833.58439 → 1876.73946
UPDATE public.match_history SET
  user_rating_before = 1872.7288885229275,
  user_rating_after = 1876.7394599957242,
  user_rd_before = 89.63975184160745,
  user_rd_after = 89.31704980992522,
  user_vol_before = 0.059975073971465655,
  user_vol_after = 0.05997415243259827,
  rating_change = 4.010571472796755
WHERE id = 2960 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2961 [lose]: before 1833.58439 → 1876.73946, after 1751.84764 → 1837.52869
UPDATE public.match_history SET
  user_rating_before = 1876.7394599957242,
  user_rating_after = 1837.528690830994,
  user_rd_before = 89.31704980992522,
  user_rd_after = 88.91250280814505,
  user_vol_before = 0.05997415243259827,
  user_vol_after = 0.05998259844412933,
  rating_change = -39.21076916473021
WHERE id = 2961 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- Session: 51c63584-e912-467b-8584-acd285e540d1
-- id=2962 [win]: before 1696.19394 → 1837.52869, after 1701.97588 → 1843.08805
UPDATE public.match_history SET
  user_rating_before = 1837.528690830994,
  user_rating_after = 1843.0880456564053,
  user_rd_before = 88.91250280814505,
  user_rd_after = 88.29155796938655,
  user_vol_before = 0.05998259844412933,
  user_vol_after = 0.05998140886640007,
  rating_change = 5.559354825411219
WHERE id = 2962 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2963 [win]: before 1701.97588 → 1843.08805, after 1705.69478 → 1846.45629
UPDATE public.match_history SET
  user_rating_before = 1843.0880456564053,
  user_rating_after = 1846.4562930829388,
  user_rd_before = 88.29155796938655,
  user_rd_after = 88.12907426240275,
  user_vol_before = 0.05998140886640007,
  user_vol_after = 0.05998058868742917,
  rating_change = 3.3682474265335713
WHERE id = 2963 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2964 [win]: before 1705.69478 → 1846.45629, after 1711.72415 → 1852.17168
UPDATE public.match_history SET
  user_rating_before = 1846.4562930829388,
  user_rating_after = 1852.1716802675721,
  user_rd_before = 88.12907426240275,
  user_rd_after = 87.50297935415563,
  user_vol_before = 0.05998058868742917,
  user_vol_after = 0.05997936902471288,
  rating_change = 5.7153871846333
WHERE id = 2964 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2965 [win]: before 1711.72415 → 1852.17168, after 1718.73236 → 1858.92587
UPDATE public.match_history SET
  user_rating_before = 1852.1716802675721,
  user_rating_after = 1858.9258736406912,
  user_rd_before = 87.50297935415563,
  user_rd_after = 86.71722852242046,
  user_vol_before = 0.05997936902471288,
  user_vol_after = 0.05997802035304114,
  rating_change = 6.754193373119051
WHERE id = 2965 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2966 [win]: before 1718.73236 → 1858.92587, after 1726.26663 → 1866.13840
UPDATE public.match_history SET
  user_rating_before = 1858.9258736406912,
  user_rating_after = 1866.138400650982,
  user_rd_before = 86.71722852242046,
  user_rd_after = 85.86389661491974,
  user_vol_before = 0.05997802035304114,
  user_vol_after = 0.05997659518617823,
  rating_change = 7.212527010290842
WHERE id = 2966 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2967 [lose]: before 1726.26663 → 1866.13840, after 1710.29477 → 1832.86751
UPDATE public.match_history SET
  user_rating_before = 1866.138400650982,
  user_rating_after = 1832.86750568348,
  user_rd_before = 85.86389661491974,
  user_rd_after = 85.03537217207072,
  user_vol_before = 0.05997659518617823,
  user_vol_after = 0.05998282614949211,
  rating_change = -33.270894967502045
WHERE id = 2967 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- Session: 6e2b5252-c749-418d-92c6-69962a7c8945
-- id=2968 [win]: before 1710.29477 → 1832.86751, after 1715.28575 → 1837.62601
UPDATE public.match_history SET
  user_rating_before = 1832.86750568348,
  user_rating_after = 1837.6260066420728,
  user_rd_before = 85.03537217207072,
  user_rd_after = 84.65876993581261,
  user_vol_before = 0.05998282614949211,
  user_vol_after = 0.05998169398182248,
  rating_change = 4.758500958592776
WHERE id = 2968 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2969 [win]: before 1715.28575 → 1837.62601, after 1722.10094 → 1844.31320
UPDATE public.match_history SET
  user_rating_before = 1837.6260066420728,
  user_rating_after = 1844.3132037838081,
  user_rd_before = 84.65876993581261,
  user_rd_after = 83.95539337575711,
  user_vol_before = 0.05998169398182248,
  user_vol_after = 0.059980291168055776,
  rating_change = 6.687197141735396
WHERE id = 2969 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2970 [win]: before 1722.10094 → 1844.31320, after 1725.54949 → 1847.42052
UPDATE public.match_history SET
  user_rating_before = 1844.3132037838081,
  user_rating_after = 1847.4205243040733,
  user_rd_before = 83.95539337575711,
  user_rd_after = 83.9201757072957,
  user_vol_before = 0.059980291168055776,
  user_vol_after = 0.05997945831909603,
  rating_change = 3.107320520265148
WHERE id = 2970 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2971 [win]: before 1725.54949 → 1847.42052, after 1728.85063 → 1850.35428
UPDATE public.match_history SET
  user_rating_before = 1847.4205243040733,
  user_rating_after = 1850.3542841188441,
  user_rd_before = 83.9201757072957,
  user_rd_after = 83.91806736196108,
  user_vol_before = 0.05997945831909603,
  user_vol_after = 0.05997866003839044,
  rating_change = 2.9337598147708377
WHERE id = 2971 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2972 [win]: before 1728.85063 → 1850.35428, after 1735.67356 → 1856.89482
UPDATE public.match_history SET
  user_rating_before = 1850.3542841188441,
  user_rating_after = 1856.8948207387828,
  user_rd_before = 83.91806736196108,
  user_rd_after = 83.2743990214202,
  user_vol_before = 0.05997866003839044,
  user_vol_after = 0.059977280073884316,
  rating_change = 6.540536619938621
WHERE id = 2972 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2973 [win]: before 1735.67356 → 1856.89482, after 1740.61303 → 1861.36939
UPDATE public.match_history SET
  user_rating_before = 1856.8948207387828,
  user_rating_after = 1861.3693884359923,
  user_rd_before = 83.2743990214202,
  user_rd_after = 82.9899913661097,
  user_vol_before = 0.059977280073884316,
  user_vol_after = 0.059976165944194845,
  rating_change = 4.4745676972095225
WHERE id = 2973 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2974 [win]: before 1740.61303 → 1861.36939, after 1744.39919 → 1864.67780
UPDATE public.match_history SET
  user_rating_before = 1861.3693884359923,
  user_rating_after = 1864.67779942633,
  user_rd_before = 82.9899913661097,
  user_rd_after = 82.92698774976083,
  user_vol_before = 0.059976165944194845,
  user_vol_after = 0.05997526755469193,
  rating_change = 3.308410990337734
WHERE id = 2974 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2975 [win]: before 1744.39919 → 1864.67780, after 1748.86059 → 1868.66542
UPDATE public.match_history SET
  user_rating_before = 1864.67779942633,
  user_rating_after = 1868.6654207764439,
  user_rd_before = 82.92698774976083,
  user_rd_after = 82.7541316683202,
  user_vol_before = 0.05997526755469193,
  user_vol_after = 0.05997425623010242,
  rating_change = 3.987621350113841
WHERE id = 2975 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2976 [win]: before 1748.86059 → 1868.66542, after 1753.67828 → 1872.91927
UPDATE public.match_history SET
  user_rating_before = 1868.6654207764439,
  user_rating_after = 1872.9192704645586,
  user_rd_before = 82.7541316683202,
  user_rd_after = 82.51705723418846,
  user_vol_before = 0.05997425623010242,
  user_vol_after = 0.0599731664644198,
  rating_change = 4.253849688114769
WHERE id = 2976 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2977 [win]: before 1753.67828 → 1872.91927, after 1760.73767 → 1879.44538
UPDATE public.match_history SET
  user_rating_before = 1872.9192704645586,
  user_rating_after = 1879.4453799931384,
  user_rd_before = 82.51705723418846,
  user_rd_after = 81.9080157372693,
  user_vol_before = 0.0599731664644198,
  user_vol_after = 0.059971754415430144,
  rating_change = 6.526109528579809
WHERE id = 2977 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2978 [win]: before 1760.73767 → 1879.44538, after 1767.13184 → 1885.21196
UPDATE public.match_history SET
  user_rating_before = 1879.4453799931384,
  user_rating_after = 1885.2119616683676,
  user_rd_before = 81.9080157372693,
  user_rd_after = 81.43020949866502,
  user_vol_before = 0.059971754415430144,
  user_vol_after = 0.05997041241216671,
  rating_change = 5.76658167522919
WHERE id = 2978 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2979 [lose]: before 1767.13184 → 1885.21196, after 1747.48267 → 1852.20104
UPDATE public.match_history SET
  user_rating_before = 1885.2119616683676,
  user_rating_after = 1852.201043367704,
  user_rd_before = 81.43020949866502,
  user_rd_after = 81.2400306694685,
  user_vol_before = 0.05997041241216671,
  user_vol_after = 0.059978925950759106,
  rating_change = -33.01091830066366
WHERE id = 2979 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- Session: b09a57f8-0ca8-4cf1-bfce-152b4f08a3e8
-- id=2980 [win]: before 1747.48267 → 1852.20104, after 1753.06263 → 1857.40182
UPDATE public.match_history SET
  user_rating_before = 1852.201043367704,
  user_rating_after = 1857.401824952358,
  user_rd_before = 81.2400306694685,
  user_rd_after = 80.87396545114733,
  user_vol_before = 0.059978925950759106,
  user_vol_after = 0.059977652246538955,
  rating_change = 5.200781584654123
WHERE id = 2980 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2981 [win]: before 1753.06263 → 1857.40182, after 1756.94151 → 1860.86977
UPDATE public.match_history SET
  user_rating_before = 1857.401824952358,
  user_rating_after = 1860.86977306331,
  user_rd_before = 80.87396545114733,
  user_rd_after = 80.81923121256989,
  user_vol_before = 0.059977652246538955,
  user_vol_after = 0.05997668230527778,
  rating_change = 3.4679481109519656
WHERE id = 2981 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2982 [win]: before 1756.94151 → 1860.86977, after 1760.84063 → 1864.35050
UPDATE public.match_history SET
  user_rating_before = 1860.86977306331,
  user_rating_after = 1864.350502037057,
  user_rd_before = 80.81923121256989,
  user_rd_after = 80.76809448896152,
  user_vol_before = 0.05997668230527778,
  user_vol_after = 0.059975716092772975,
  rating_change = 3.4807289737468636
WHERE id = 2982 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2983 [win]: before 1760.84063 → 1864.35050, after 1766.61262 → 1869.65775
UPDATE public.match_history SET
  user_rating_before = 1864.350502037057,
  user_rating_after = 1869.657749847561,
  user_rd_before = 80.76809448896152,
  user_rd_after = 80.39910508789032,
  user_vol_before = 0.059975716092772975,
  user_vol_after = 0.059974422361063234,
  rating_change = 5.307247810504123
WHERE id = 2983 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2984 [win]: before 1766.61262 → 1869.65775, after 1771.05862 → 1873.61581
UPDATE public.match_history SET
  user_rating_before = 1869.657749847561,
  user_rating_after = 1873.6158145449635,
  user_rd_before = 80.39910508789032,
  user_rd_after = 80.2665813066181,
  user_vol_before = 0.059974422361063234,
  user_vol_after = 0.05997334705502713,
  rating_change = 3.9580646974025058
WHERE id = 2984 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2985 [win]: before 1771.05862 → 1873.61581, after 1774.38144 → 1876.50568
UPDATE public.match_history SET
  user_rating_before = 1873.6158145449635,
  user_rating_after = 1876.5056772601818,
  user_rd_before = 80.2665813066181,
  user_rd_after = 80.33712841740716,
  user_vol_before = 0.05997334705502713,
  user_vol_after = 0.059972504722139414,
  rating_change = 2.8898627152182144
WHERE id = 2985 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2986 [win]: before 1774.38144 → 1876.50568, after 1782.95638 → 1884.66479
UPDATE public.match_history SET
  user_rating_before = 1876.5056772601818,
  user_rating_after = 1884.6647863048884,
  user_rd_before = 80.33712841740716,
  user_rd_after = 79.56268488647471,
  user_vol_before = 0.059972504722139414,
  user_vol_after = 0.059970938587570154,
  rating_change = 8.15910904470661
WHERE id = 2986 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2987 [win]: before 1782.95638 → 1884.66479, after 1786.36546 → 1887.61668
UPDATE public.match_history SET
  user_rating_before = 1884.6647863048884,
  user_rating_after = 1887.6166808493313,
  user_rd_before = 79.56268488647471,
  user_rd_after = 79.64154897199448,
  user_vol_before = 0.059970938587570154,
  user_vol_after = 0.05997008233037314,
  rating_change = 2.9518945444428937
WHERE id = 2987 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2988 [win]: before 1786.36546 → 1887.61668, after 1789.63699 → 1890.40354
UPDATE public.match_history SET
  user_rating_before = 1887.6166808493313,
  user_rating_after = 1890.4035355469207,
  user_rd_before = 79.64154897199448,
  user_rd_after = 79.73890603170908,
  user_vol_before = 0.05997008233037314,
  user_vol_after = 0.0599692491537413,
  rating_change = 2.7868546975894333
WHERE id = 2988 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2989 [win]: before 1789.63699 → 1890.40354, after 1799.46189 → 1899.88070
UPDATE public.match_history SET
  user_rating_before = 1890.4035355469207,
  user_rating_after = 1899.8807016867045,
  user_rd_before = 79.73890603170908,
  user_rd_after = 78.86259472680158,
  user_vol_before = 0.0599692491537413,
  user_vol_after = 0.05996771539349684,
  rating_change = 9.477166139783776
WHERE id = 2989 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2990 [win]: before 1799.46189 → 1899.88070, after 1806.95644 → 1906.69605
UPDATE public.match_history SET
  user_rating_before = 1899.8807016867045,
  user_rating_after = 1906.6960465355455,
  user_rd_before = 78.86259472680158,
  user_rd_after = 78.31777287497395,
  user_vol_before = 0.05996771539349684,
  user_vol_after = 0.05996621507691681,
  rating_change = 6.81534484884105
WHERE id = 2990 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2991 [win]: before 1806.95644 → 1906.69605, after 1812.94870 → 1912.00505
UPDATE public.match_history SET
  user_rating_before = 1906.6960465355455,
  user_rating_after = 1912.0050515893754,
  user_rd_before = 78.31777287497395,
  user_rd_after = 78.0203012961003,
  user_vol_before = 0.05996621507691681,
  user_vol_after = 0.059964891252725416,
  rating_change = 5.309005053829878
WHERE id = 2991 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2992 [win]: before 1812.94870 → 1912.00505, after 1815.83104 → 1914.39064
UPDATE public.match_history SET
  user_rating_before = 1912.0050515893754,
  user_rating_after = 1914.3906394688154,
  user_rd_before = 78.0203012961003,
  user_rd_after = 78.2194120252533,
  user_vol_before = 0.059964891252725416,
  user_vol_after = 0.059964131533276094,
  rating_change = 2.3855878794399814
WHERE id = 2992 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2993 [win]: before 1815.83104 → 1914.39064, after 1821.14398 → 1918.97628
UPDATE public.match_history SET
  user_rating_before = 1914.3906394688154,
  user_rating_after = 1918.9762848306027,
  user_rd_before = 78.2194120252533,
  user_rd_after = 78.02364858505736,
  user_vol_before = 0.059964131533276094,
  user_vol_after = 0.059962893259074425,
  rating_change = 4.5856453617873285
WHERE id = 2993 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2994 [win]: before 1815.83104 → 1918.97628, after 1820.33451 → 1922.70695
UPDATE public.match_history SET
  user_rating_before = 1918.9762848306027,
  user_rating_after = 1922.7069545825002,
  user_rd_before = 78.02364858505736,
  user_rd_after = 77.97827852593574,
  user_vol_before = 0.059962893259074425,
  user_vol_after = 0.059961816522890884,
  rating_change = 3.7306697518974943
WHERE id = 2994 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2995 [win]: before 1815.83104 → 1922.70695, after 1820.39630 → 1926.41671
UPDATE public.match_history SET
  user_rating_before = 1922.7069545825002,
  user_rating_after = 1926.4167066371876,
  user_rd_before = 77.97827852593574,
  user_rd_after = 77.93612928799008,
  user_vol_before = 0.059961816522890884,
  user_vol_after = 0.05996074114127946,
  rating_change = 3.709752054687442
WHERE id = 2995 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2996 [win]: before 1815.83104 → 1926.41671, after 1819.36491 → 1929.17751
UPDATE public.match_history SET
  user_rating_before = 1926.4167066371876,
  user_rating_after = 1929.1775064834528,
  user_rd_before = 77.93612928799008,
  user_rd_after = 78.06671496408474,
  user_vol_before = 0.05996074114127946,
  user_vol_after = 0.05995988483952911,
  rating_change = 2.760799846265172
WHERE id = 2996 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=2997 [lose]: before 1815.83104 → 1929.17751, after 1795.19662 → 1898.57155
UPDATE public.match_history SET
  user_rating_before = 1929.1775064834528,
  user_rating_after = 1898.5715516614725,
  user_rd_before = 78.06671496408474,
  user_rd_after = 78.08839381701496,
  user_vol_before = 0.05995988483952911,
  user_vol_after = 0.0599686754823952,
  rating_change = -30.605954821980276
WHERE id = 2997 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- Session: 4b78fac3-18f8-4890-82e1-ff089e89d171
-- id=2998 [lose]: before 1795.19662 → 1898.57155, after 1773.68942 → 1867.34187
UPDATE public.match_history SET
  user_rating_before = 1898.5715516614725,
  user_rating_after = 1867.3418687948483,
  user_rd_before = 78.08839381701496,
  user_rd_after = 78.17261967739402,
  user_vol_before = 0.0599686754823952,
  user_vol_after = 0.05997797085613877,
  rating_change = -31.229682866624216
WHERE id = 2998 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- Session: 1be1102e-212d-4fed-b984-93292a5b4bd2
-- id=2999 [win]: before 1773.68942 → 1867.34187, after 1776.92005 → 1870.06786
UPDATE public.match_history SET
  user_rating_before = 1867.3418687948483,
  user_rating_after = 1870.0678619951134,
  user_rd_before = 78.17261967739402,
  user_rd_after = 78.30713372618658,
  user_vol_before = 0.05997797085613877,
  user_vol_after = 0.05997712843332937,
  rating_change = 2.7259932002650658
WHERE id = 2999 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- Session: 9a82c462-6a2e-41f9-ad6c-fb7d5a19a003
-- id=3000 [win]: before 1776.92005 → 1870.06786, after 1779.33302 → 1872.07755
UPDATE public.match_history SET
  user_rating_before = 1870.0678619951134,
  user_rating_after = 1872.0775450181923,
  user_rd_before = 78.30713372618658,
  user_rd_after = 78.57944752762903,
  user_vol_before = 0.05997712843332937,
  user_vol_after = 0.05997648275715422,
  rating_change = 2.0096830230788783
WHERE id = 3000 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3001 [lose]: before 1779.33302 → 1872.07755, after 1758.40455 → 1841.68464
UPDATE public.match_history SET
  user_rating_before = 1872.0775450181923,
  user_rating_after = 1841.68464283034,
  user_rd_before = 78.57944752762903,
  user_rd_after = 78.43748503622993,
  user_vol_before = 0.05997648275715422,
  user_vol_after = 0.059984657512775916,
  rating_change = -30.392902187852314
WHERE id = 3001 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- Session: b8824737-c07c-43d1-b068-a805086e855f
-- id=3052 [win]: before 1819.90798 → 1824.14960, after 1824.10836 → 1828.27473
UPDATE public.match_history SET
  user_rating_before = 1824.14960244343,
  user_rating_after = 1828.2747307915097,
  user_rd_before = 69.5325578022292,
  user_rd_after = 69.61286698279044,
  user_vol_before = 0.0599587514105382,
  user_vol_after = 0.05995741553308351,
  rating_change = 4.12512834807967
WHERE id = 3052 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3053 [win]: before 1819.90798 → 1828.27473, after 1823.69443 → 1831.92790
UPDATE public.match_history SET
  user_rating_before = 1828.2747307915097,
  user_rating_after = 1831.9279010449563,
  user_rd_before = 69.61286698279044,
  user_rd_after = 69.76118100932095,
  user_vol_before = 0.05995741553308351,
  user_vol_after = 0.05995618230669618,
  rating_change = 3.6531702534466604
WHERE id = 3053 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3054 [win]: before 1819.90798 → 1831.92790, after 1822.38810 → 1834.28051
UPDATE public.match_history SET
  user_rating_before = 1831.9279010449563,
  user_rating_after = 1834.2805136935588,
  user_rd_before = 69.76118100932095,
  user_rd_after = 70.10649198652891,
  user_vol_before = 0.05995618230669618,
  user_vol_after = 0.05995528485622952,
  rating_change = 2.352612648602417
WHERE id = 3054 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3055 [win]: before 1819.90798 → 1834.28051, after 1822.93548 → 1837.15555
UPDATE public.match_history SET
  user_rating_before = 1834.2805136935588,
  user_rating_after = 1837.155547973328,
  user_rd_before = 70.10649198652891,
  user_rd_after = 70.37424499806505,
  user_vol_before = 0.05995528485622952,
  user_vol_after = 0.05995427657896248,
  rating_change = 2.875034279769352
WHERE id = 3055 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3056 [win]: before 1819.90798 → 1837.15555, after 1822.64029 → 1839.72541
UPDATE public.match_history SET
  user_rating_before = 1837.155547973328,
  user_rating_after = 1839.7254050283702,
  user_rd_before = 70.37424499806505,
  user_rd_after = 70.67399386740264,
  user_vol_before = 0.05995427657896248,
  user_vol_after = 0.059953330991949424,
  rating_change = 2.569857055042121
WHERE id = 3056 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3057 [win]: before 1819.90798 → 1839.72541, after 1824.42076 → 1843.97729
UPDATE public.match_history SET
  user_rating_before = 1839.7254050283702,
  user_rating_after = 1843.9772934342627,
  user_rd_before = 70.67399386740264,
  user_rd_after = 70.70581287615074,
  user_vol_before = 0.059953330991949424,
  user_vol_after = 0.05995199060732114,
  rating_change = 4.251888405892487
WHERE id = 3057 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3058 [win]: before 1819.90798 → 1843.97729, after 1823.83128 → 1847.59563
UPDATE public.match_history SET
  user_rating_before = 1843.9772934342627,
  user_rating_after = 1847.5956262914774,
  user_rd_before = 70.70581287615074,
  user_rd_after = 70.83354130410777,
  user_vol_before = 0.05995199060732114,
  user_vol_after = 0.059950786601871295,
  rating_change = 3.618332857214682
WHERE id = 3058 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3059 [win]: before 1819.90798 → 1847.59563, after 1824.15202 → 1851.46498
UPDATE public.match_history SET
  user_rating_before = 1847.5956262914774,
  user_rating_after = 1851.4649759356787,
  user_rd_before = 70.83354130410777,
  user_rd_after = 70.92463703353866,
  user_vol_before = 0.059950786601871295,
  user_vol_after = 0.05994954039929199,
  rating_change = 3.869349644201293
WHERE id = 3059 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3060 [win]: before 1819.90798 → 1851.46498, after 1825.28467 → 1856.33816
UPDATE public.match_history SET
  user_rating_before = 1851.4649759356787,
  user_rating_after = 1856.33816280004,
  user_rd_before = 70.92463703353866,
  user_rd_after = 70.89067457475767,
  user_vol_before = 0.05994954039929199,
  user_vol_after = 0.059948162824882995,
  rating_change = 4.873186864361287
WHERE id = 3060 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3061 [win]: before 1819.90798 → 1856.33816, after 1822.18112 → 1858.30445
UPDATE public.match_history SET
  user_rating_before = 1856.33816280004,
  user_rating_after = 1858.3044510223629,
  user_rd_before = 70.89067457475767,
  user_rd_after = 71.2879932433193,
  user_vol_before = 0.059948162824882995,
  user_vol_after = 0.05994742139462812,
  rating_change = 1.9662882223228735
WHERE id = 3061 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3062 [win]: before 1819.90798 → 1858.30445, after 1822.05793 → 1860.15868
UPDATE public.match_history SET
  user_rating_before = 1858.3044510223629,
  user_rating_after = 1860.1586805878906,
  user_rd_before = 71.2879932433193,
  user_rd_after = 71.69325767358933,
  user_vol_before = 0.05994742139462812,
  user_vol_after = 0.05994671156664172,
  rating_change = 1.854229565527703
WHERE id = 3062 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3063 [win]: before 1819.90798 → 1860.15868, after 1824.20562 → 1863.92857
UPDATE public.match_history SET
  user_rating_before = 1860.1586805878906,
  user_rating_after = 1863.9285670084637,
  user_rd_before = 71.69325767358933,
  user_rd_after = 71.77146911206958,
  user_vol_before = 0.05994671156664172,
  user_vol_after = 0.059945487146131196,
  rating_change = 3.7698864205731297
WHERE id = 3063 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3064 [win]: before 1819.90798 → 1863.92857, after 1825.89658 → 1869.17882
UPDATE public.match_history SET
  user_rating_before = 1863.9285670084637,
  user_rating_after = 1869.1788158354598,
  user_rd_before = 71.77146911206958,
  user_rd_after = 71.64250379589294,
  user_vol_before = 0.059945487146131196,
  user_vol_after = 0.059944027792152,
  rating_change = 5.250248826996085
WHERE id = 3064 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- id=3065 [lose]: before 1819.90798 → 1869.17882, after 1795.58666 → 1842.57661
UPDATE public.match_history SET
  user_rating_before = 1869.1788158354598,
  user_rating_after = 1842.576605025075,
  user_rd_before = 71.64250379589294,
  user_rd_after = 71.92924591110294,
  user_vol_before = 0.059944027792152,
  user_vol_after = 0.05995350244172479,
  rating_change = -26.602210810384804
WHERE id = 3065 AND user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b';

-- Update user_mode_ratings to final chained value
UPDATE public.user_mode_ratings SET
  rating = 1842.576605025075,
  rd = 71.92924591110294,
  vol = 0.05995350244172479
WHERE user_id = 'e2a3fcaa-bfb7-41e2-84fa-b6f32b1d8b9b' AND mode = 'global';

COMMIT;